- name: "add node.js from node source"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | bash -

- name: "add node.js from node source"
  become: true
  apt: 
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name : pm2
    global: yes


